### ISSUE TITLE
Issue 10 - Level 1 Sylvia Bug

### ISSUE THREAD

**Issue by JodieAsh** [mrabone94/AstonAdventure#10]
Bug in level 1 where when Sylvia first approaches you she disappears on her way off the screen.
Also consider timings between meeting this character (are they too close together?).

**Comment by mrabone94** [comment]
Increased gaps between when Sylvia approaches the player after the first time after starting the level with commit 2b8dada3c6e31b416cacf9878d4ad754bcb4ee80

Issue with Sylvia dissappearing when she leaves the screen still outstanding
