### ISSUE TITLE
Issue 14 - Refactor Code 

### ISSUE THREAD

**Issue by JodieAsh** [mrabone94/AstonAdventure#14]
Lots of repeated code in the items class.

**Comment by JodieAsh** [comment]
Much bigger problem than first appeared to be. 
Text class and Level One class both depend on this code to work. 
Lots of it is hard-coded. I suggest we make an Item class that allows us to add any 'item' that we want into the game (a template class). 
This will make it much simpler to expand and make more levels.

**Comment by JodieAsh** [comment]
Have been working on this refactor all day.
Classes 'Inventory', 'Text', 'LevelOne' and 'Items' are heavily coupled.  
We need to sort out a code review system to avoid issues like this from occurring in the future. 
Also because this refactor is very large it would be nice if somebody could review my code before it's pushed.

**Comment by JodieAsh** [comment]
Note any new items must be added to the ItemType enum class and their file-paths must be added to the item file paths hashMap in items. 
(This is not perfect if anybody has any suggestions on how to improve this please let me know)

This is a partial refactor. There is still a lot of work left to do.
In particular the text class (Sylvia's code) still needs a lot of work.

**Comment by mrabone94** [comment]
Moved HashMap in Item class to a collective class GameItems so its easier to read in commit db7446b4b62e4439750911758c786227eb2e9504. Minor change but hopefully aids code readability

**Comment by JodieAsh** [comment]
db7446b 

@mrabone94 Just curious as to why you did this?
How does this aid code readability?
Now there are two classes that claim to be related to items, this could lead to confusion.

**Comment by JodieAsh** [comment]
08e3a5e 
Renamed the 'gameItems' class. This clears up my confusion. Don't read code late at night kids.

**Comment by JodieAsh** [comment]
New issue opened addressing what to refactor next. #23
