### ISSUE TITLE
Issue 8 - Add running shoes to level 2 

### ISSUE THREAD

**Issue by JodieAsh** [mrabone94/AstonAdventure#8]
Level 2 currently takes a long time to complete. 
Adding shoes to this would help to speed up the level making it more enjoyable.

**Comment by JodieAsh** [comment]
See issue #14 
(Due to lots of the item code currently being hard-coded) 
I don't think we should add any more items into the game until we've completed the Item class refactor.

**Comment by JodieAsh** [comment]
Discovered bug where items appear in-front of the player.

In addition, commit da0228b is probably not the best way to add items into the game, it involves lots of repeated code. The method (code) to check whether or not an item is being picked up should probably not be repeated in each level #14 . 

Also, you can currently pick the shoes up before you have the backpack (and therefore option to display the inventory).

**Comment by mrabone94** [comment]
> Also, you can currently pick the shoes up before you have the backpack (and therefore option to display the inventory

Issue #20 has been opened to address this
